HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
bindkey -v

setopt SHARE_HISTORY
setopt HIST_IGNORE_DUPS

zstyle :compinstall filename '/home/abc/.zshrc'
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}'
zstyle ':completion:*' menu select

autoload -Uz compinit
compinit

# Add aliases here
alias n='nvim'

alias eza-base="eza --smart-group --icons --group-directories-first --time-style=$'+%Y-%m-%d %H\n%m-%d %H:%M:%S'"
alias e='eza-base -l'
alias eu='eza-base -al'
alias em='eza-base -al --sort=modified'
alias es='eza-base -al --sort=size'
alias et='eza --icons --tree --level=2'
alias ed="eza -al --smart-group --icons --only-dirs --time-style=$'+%Y-%m-%d %H\n%m-%d %H:%M:%S'"

eval "$(zoxide init zsh)"
eval "$(fnm env --use-on-cd --shell zsh)"
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
eval "$(starship init zsh)"
source /usr/share/zsh/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh
